-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4ef03c4223ad322c7adaa6c6c0efb26b57df3b71
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 3b296326393ad9130469e1df921e912d31e67fe1
    hooks:
    -   id: forbid-tabs
