-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 6b1aa19425b35f8c34f43ada8f1045b028dc19a5
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 0f5055d31f39ea3ac1f5335a0cca320200cd0c51
    hooks:
    -   id: forbid-tabs